// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDNlDWpNubogZE0ScuKm2nySRSVzbxcS8',
    appId: '1:529215388953:web:a1e88b632bbd2dd1005988',
    messagingSenderId: '529215388953',
    projectId: 'nomadefinalproject',
    authDomain: 'nomadefinalproject.firebaseapp.com',
    storageBucket: 'nomadefinalproject.firebasestorage.app',
    measurementId: 'G-TNXZE0J9XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf7ZP8cmCUTqmwGWxi-pD21KmFJ4n6Pto',
    appId: '1:529215388953:android:bcf87b4e8ace6e7c005988',
    messagingSenderId: '529215388953',
    projectId: 'nomadefinalproject',
    storageBucket: 'nomadefinalproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbie_nbZNpuS1FS-D7y-zwy-6lJtH0FSo',
    appId: '1:529215388953:ios:7db6535e18f4fd35005988',
    messagingSenderId: '529215388953',
    projectId: 'nomadefinalproject',
    storageBucket: 'nomadefinalproject.firebasestorage.app',
    iosBundleId: 'com.example.nomadeFinalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbie_nbZNpuS1FS-D7y-zwy-6lJtH0FSo',
    appId: '1:529215388953:ios:7db6535e18f4fd35005988',
    messagingSenderId: '529215388953',
    projectId: 'nomadefinalproject',
    storageBucket: 'nomadefinalproject.firebasestorage.app',
    iosBundleId: 'com.example.nomadeFinalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDNlDWpNubogZE0ScuKm2nySRSVzbxcS8',
    appId: '1:529215388953:web:477e2f6721778627005988',
    messagingSenderId: '529215388953',
    projectId: 'nomadefinalproject',
    authDomain: 'nomadefinalproject.firebaseapp.com',
    storageBucket: 'nomadefinalproject.firebasestorage.app',
    measurementId: 'G-J8NLPX4QJR',
  );

}