// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCSU1fKZ7V3pVCdsDFDRhb8kHsXgPxlSc',
    appId: '1:98010972177:web:46fe0ea4bc3b3f0116b1b0',
    messagingSenderId: '98010972177',
    projectId: 'tictok-clone-86eea',
    authDomain: 'tictok-clone-86eea.firebaseapp.com',
    storageBucket: 'tictok-clone-86eea.firebasestorage.app',
    measurementId: 'G-PN5SZKP6PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkNxSKwq4FITDNcVqMQcp9cVNNn09qSNE',
    appId: '1:98010972177:android:dbc4fa7cae35a09316b1b0',
    messagingSenderId: '98010972177',
    projectId: 'tictok-clone-86eea',
    storageBucket: 'tictok-clone-86eea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUyfNF51wPpjlEAslySqwppjGw5LsGbQM',
    appId: '1:98010972177:ios:ce7a055e7281fe1616b1b0',
    messagingSenderId: '98010972177',
    projectId: 'tictok-clone-86eea',
    storageBucket: 'tictok-clone-86eea.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUyfNF51wPpjlEAslySqwppjGw5LsGbQM',
    appId: '1:98010972177:ios:ce7a055e7281fe1616b1b0',
    messagingSenderId: '98010972177',
    projectId: 'tictok-clone-86eea',
    storageBucket: 'tictok-clone-86eea.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCSU1fKZ7V3pVCdsDFDRhb8kHsXgPxlSc',
    appId: '1:98010972177:web:ccc2906d10a24b8016b1b0',
    messagingSenderId: '98010972177',
    projectId: 'tictok-clone-86eea',
    authDomain: 'tictok-clone-86eea.firebaseapp.com',
    storageBucket: 'tictok-clone-86eea.firebasestorage.app',
    measurementId: 'G-TG997NF05K',
  );
}
