const interests = [
  "Daily Life",
  "Comedy",
  "Entertainment",
  "Animals",
  "Food",
  "Beauty & Style",
  "Drama",
  "Learning",
  "Talent",
  "Sports",
  "Auto",
  "Family",
  "Fitness & Health",
  "DIY & Life Hacks",
  "Arts & Crafts",
  "Dance",
  "Outdoors",
  "Oddly Satisfying",
  "Home & Garden",
  "Daily Life",
  "Comedy",
  "Entertainment",
  "Animals",
  "Food",
  "Beauty & Style",
  "Drama",
  "Learning",
  "Talent",
  "Sports",
  "Auto",
  "Family",
  "Fitness & Health",
  "DIY & Life Hacks",
  "Arts & Crafts",
  "Dance",
  "Outdoors",
  "Oddly Satisfying",
  "Home & Garden",
];

const interestsWithSub = {
  "Daily Life": [
    "Vlogs",
    "Morning Routine",
    "Night Routine",
    "Study With Me",
    "Work From Home",
    "Shopping Hauls",
    "Room Tours",
    "Daily Planning",
    "Minimalist Living",
    "Pet Daily Life",
  ],
  "Comedy": [
    "Stand-up",
    "Sketch",
    "Parody",
    "Pranks",
    "Funny Moments",
    "Dark Humor",
    "Memes",
    "Situational Comedy",
    "Slapstick",
    "Impressions",
  ],
  "Entertainment": [
    "Movie Reviews",
    "TV Show Clips",
    "Celebrity Gossip",
    "Game Shows",
    "Talk Shows",
    "Drama Recaps",
    "Theater",
    "Music Shows",
    "Concert Highlights",
    "Awards Shows",
  ],
  "Animals": [
    "Cute Pets",
    "Wildlife",
    "Animal Rescues",
    "Training Tips",
    "Funny Animals",
    "Exotic Pets",
    "Aquarium Life",
    "Farm Animals",
    "Bird Watching",
    "Animal Vlogs",
  ],
  "Food": [
    "Cooking Recipes",
    "Street Food",
    "Mukbang",
    "Food Challenges",
    "Baking",
    "Restaurant Reviews",
    "Vegan Recipes",
    "Korean Food",
    "Japanese Food",
    "Fast Food Hacks",
  ],
  "Beauty & Style": [
    "Makeup Tutorials",
    "Skincare",
    "Hair Styling",
    "Nail Art",
    "Fashion Trends",
    "Outfit Ideas",
    "Closet Tours",
    "Perfume Reviews",
    "Jewelry Styling",
    "Wardrobe Essentials",
  ],
  "Drama": [
    "K-Drama",
    "Western Drama",
    "Romance Scenes",
    "Action Scenes",
    "Thriller Clips",
    "Fan Edits",
    "Behind the Scenes",
    "Drama OST",
    "Historical Drama",
    "Fantasy Drama",
  ],
  "Learning": [
    "Math Lessons",
    "Science Experiments",
    "History Shorts",
    "Language Learning",
    "Coding Basics",
    "Art History",
    "Psychology Tips",
    "Philosophy",
    "Geography",
    "Economics Basics",
  ],
  "Talent": [
    "Singing",
    "Dancing",
    "Magic Tricks",
    "Acting",
    "Impressions",
    "Beatboxing",
    "Instrument Covers",
    "Freestyle Rap",
    "Drawing Speedrun",
    "Storytelling",
  ],
  "Sports": [
    "Soccer Highlights",
    "Basketball Highlights",
    "Baseball Highlights",
    "Tennis Matches",
    "Martial Arts",
    "Gymnastics",
    "Olympic Clips",
    "Extreme Sports",
    "Cycling",
    "Running Tips",
  ],
};
